---
logger:
  default:
    sink: logs/default.log
    rotation: 10 MB
    retention: 5
    backtrace: False
    diagnose: False
    severity: 25  # up to Success log level
  large:
    sink: logs/default_large.log
    rotation: 20 MB
    retention: 5
    level: INFO 
    backtrace: False
    diagnose: False
  warning:
    sink: logs/warning.log
    rotation: 20 MB
    retention: 5
    level: WARNING
    backtrace: True
    diagnose: False 
